server:
  port: 8090

eureka:
    registry:
        username: admin
        password: admin
    client:
        service-url:
            defaultZone: http://${eureka.registry.username}:${eureka.registry.password}@localhost:8761/eureka/
        enabled: true
        fetch-registry: true
        register-with-eureka: true

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/sc-exam
    username: root
    password:
    tomcat:
      initial-size: 5
      max-active: 30
  jpa:
      hibernate:
          ddl-auto: update
      properties:
          hibernate:
              dialect: org.hibernate.dialect.MySQL5InnoDBDialect

  thymeleaf:
    cache: false # Whether to enable template caching.
    check-template: true # Whether to check that the template exists before rendering it.
    check-template-location: true # Whether to check that the templates location exists.
    enable-spring-el-compiler: false # Enable the SpringEL compiler in SpringEL expressions.
    enabled: true # Whether to enable Thymeleaf view resolution for Web frameworks.
    encoding: UTF-8 # Template files encoding.
    mode: HTML # Template mode to be applied to templates. See also Thymeleaf''s TemplateMode enum.
    prefix: classpath:/templates/ # Prefix that gets prepended to view names when building a URL.
    servlet:
      content-type: text/html # Content-Type value written to HTTP responses.
    suffix: .html # Suffix that gets appended to view names when building a URL.
    template-resolver-order: # Order of the template resolver in the chain.

